db.Appointments.insertMany([
  {
    patientId: patient1,
    doctorId: doctor1,
    appointmentDate: new Date("2025-03-01T10:00:00"),
    status: "Scheduled",
    notes: "Routine checkup for diabetes.",
  },
  {
    patientId: patient2,
    doctorId: doctor2,
    appointmentDate: new Date("2025-03-02T11:30:00"),
    status: "Scheduled",
    notes: "Neurological consultation for migraine.",
  },
  {
    patientId: patient3,
    doctorId: doctor3,
    appointmentDate: new Date("2025-03-03T14:00:00"),
    status: "Scheduled",
    notes: "Orthopedic consultation for knee pain.",
  },
  {
    patientId: patient4,
    doctorId: doctor4,
    appointmentDate: new Date("2025-03-04T09:30:00"),
    status: "Scheduled",
    notes: "Pediatrician visit for routine checkup.",
  },
  {
    patientId: patient5,
    doctorId: doctor5,
    appointmentDate: new Date("2025-03-05T16:00:00"),
    status: "Scheduled",
    notes: "Skin allergy consultation.",
  },
  {
    patientId: patient6,
    doctorId: doctor6,
    appointmentDate: new Date("2025-03-06T12:45:00"),
    status: "Scheduled",
    notes: "General consultation for headache.",
  },
  {
    patientId: patient7,
    doctorId: doctor7,
    appointmentDate: new Date("2025-03-07T10:15:00"),
    status: "Scheduled",
    notes: "Heart checkup and ECG.",
  },
  {
    patientId: patient8,
    doctorId: doctor8,
    appointmentDate: new Date("2025-03-08T15:30:00"),
    status: "Scheduled",
    notes: "Neurology consultation for dizziness.",
  },
  {
    patientId: patient9,
    doctorId: doctor9,
    appointmentDate: new Date("2025-03-09T13:00:00"),
    status: "Scheduled",
    notes: "Back pain consultation with orthopedic.",
  },
  {
    patientId: patient10,
    doctorId: doctor10,
    appointmentDate: new Date("2025-03-10T08:30:00"),
    status: "Scheduled",
    notes: "General pediatric consultation.",
  },
  {
    patientId: patient11,
    doctorId: doctor11,
    appointmentDate: new Date("2025-03-11T17:00:00"),
    status: "Scheduled",
    notes: "Dermatology consultation for skin rash.",
  },
  {
    patientId: patient12,
    doctorId: doctor12,
    appointmentDate: new Date("2025-03-12T14:45:00"),
    status: "Scheduled",
    notes: "General consultation for joint pain.",
  },
  {
    patientId: patient13,
    doctorId: doctor13,
    appointmentDate: new Date("2025-03-13T09:00:00"),
    status: "Scheduled",
    notes: "Heart health consultation.",
  },
  {
    patientId: patient14,
    doctorId: doctor14,
    appointmentDate: new Date("2025-03-14T11:15:00"),
    status: "Scheduled",
    notes: "Neurology follow-up appointment.",
  },
  {
    patientId: patient15,
    doctorId: doctor15,
    appointmentDate: new Date("2025-03-15T16:30:00"),
    status: "Scheduled",
    notes: "Orthopedic consultation for wrist pain.",
  },
]);
