db.MedicalRecords.insertMany([
  {
    patientId: patient1,
    doctorId: doctor1,
    diagnosis: "Hypertension",
    treatment: "Advised lifestyle changes and prescribed medication.",
    medications: ["Amlodipine", "Losartan"],
    recordDate: new Date("2024-12-10"),
  },
  {
    patientId: patient2,
    doctorId: doctor2,
    diagnosis: "Chronic Migraine",
    treatment: "Prescribed migraine prevention therapy.",
    medications: ["Propranolol", "Sumatriptan"],
    recordDate: new Date("2024-11-25"),
  },
  {
    patientId: patient3,
    doctorId: doctor3,
    diagnosis: "Fractured Wrist",
    treatment: "Applied cast and prescribed painkillers.",
    medications: ["Ibuprofen"],
    recordDate: new Date("2024-10-15"),
  },
  {
    patientId: patient4,
    doctorId: doctor4,
    diagnosis: "Seasonal Flu",
    treatment: "Prescribed antiviral medication and rest.",
    medications: ["Oseltamivir"],
    recordDate: new Date("2024-09-18"),
  },
  {
    patientId: patient5,
    doctorId: doctor5,
    diagnosis: "Acne",
    treatment: "Recommended skincare routine and antibiotics.",
    medications: ["Doxycycline"],
    recordDate: new Date("2024-08-22"),
  },
  {
    patientId: patient6,
    doctorId: doctor6,
    diagnosis: "Gastric Ulcer",
    treatment: "Prescribed proton pump inhibitors.",
    medications: ["Omeprazole"],
    recordDate: new Date("2024-07-10"),
  },
  {
    patientId: patient7,
    doctorId: doctor7,
    diagnosis: "Arrhythmia",
    treatment: "Prescribed beta-blockers and advised ECG monitoring.",
    medications: ["Metoprolol"],
    recordDate: new Date("2024-06-05"),
  },
  {
    patientId: patient8,
    doctorId: doctor8,
    diagnosis: "Vertigo",
    treatment: "Recommended vestibular therapy and medication.",
    medications: ["Meclizine"],
    recordDate: new Date("2024-05-14"),
  },
  {
    patientId: patient9,
    doctorId: doctor9,
    diagnosis: "Lower Back Pain",
    treatment: "Prescribed physiotherapy and muscle relaxants.",
    medications: ["Cyclobenzaprine"],
    recordDate: new Date("2024-04-30"),
  },
  {
    patientId: patient10,
    doctorId: doctor10,
    diagnosis: "Allergic Rhinitis",
    treatment: "Advised antihistamines and nasal spray.",
    medications: ["Cetirizine", "Fluticasone"],
    recordDate: new Date("2024-03-21"),
  },
  {
    patientId: patient11,
    doctorId: doctor11,
    diagnosis: "Psoriasis",
    treatment: "Prescribed topical corticosteroids.",
    medications: ["Clobetasol"],
    recordDate: new Date("2024-02-18"),
  },
  {
    patientId: patient12,
    doctorId: doctor12,
    diagnosis: "Arthritis",
    treatment: "Advised physiotherapy and pain management.",
    medications: ["Naproxen"],
    recordDate: new Date("2024-01-12"),
  },
  {
    patientId: patient13,
    doctorId: doctor13,
    diagnosis: "Coronary Artery Disease",
    treatment: "Started on statins and advised dietary modifications.",
    medications: ["Atorvastatin"],
    recordDate: new Date("2023-12-05"),
  },
  {
    patientId: patient14,
    doctorId: doctor14,
    diagnosis: "Epilepsy",
    treatment: "Prescribed anticonvulsants and advised EEG tests.",
    medications: ["Levetiracetam"],
    recordDate: new Date("2023-11-20"),
  },
  {
    patientId: patient15,
    doctorId: doctor15,
    diagnosis: "Knee Osteoarthritis",
    treatment: "Prescribed painkillers and recommended knee braces.",
    medications: ["Diclofenac"],
    recordDate: new Date("2023-10-10"),
  },
  {
    patientId: patient3,
    doctorId: doctor7,
    diagnosis: "High Cholesterol",
    treatment: "Advised dietary control and prescribed statins.",
    medications: ["Rosuvastatin"],
    recordDate: new Date("2023-09-05"),
  },
  {
    patientId: patient6,
    doctorId: doctor9,
    diagnosis: "Rotator Cuff Injury",
    treatment: "Recommended physiotherapy and anti-inflammatory meds.",
    medications: ["Ibuprofen"],
    recordDate: new Date("2023-08-12"),
  },
  {
    patientId: patient8,
    doctorId: doctor5,
    diagnosis: "Eczema",
    treatment: "Prescribed emollients and corticosteroid cream.",
    medications: ["Hydrocortisone"],
    recordDate: new Date("2023-07-30"),
  },
  {
    patientId: patient12,
    doctorId: doctor11,
    diagnosis: "Gout",
    treatment: "Advised dietary control and prescribed uric acid reducers.",
    medications: ["Allopurinol"],
    recordDate: new Date("2023-06-22"),
  },
  {
    patientId: patient14,
    doctorId: doctor3,
    diagnosis: "Sciatica",
    treatment: "Prescribed physiotherapy and pain relievers.",
    medications: ["Gabapentin"],
    recordDate: new Date("2023-05-15"),
  },
  {
    patientId: patient10,
    doctorId: doctor1,
    diagnosis: "Bronchitis",
    treatment: "Prescribed bronchodilators and rest.",
    medications: ["Salbutamol"],
    recordDate: new Date("2023-04-10"),
  },
  {
    patientId: patient4,
    doctorId: doctor8,
    diagnosis: "Sinusitis",
    treatment: "Prescribed decongestants and antibiotics.",
    medications: ["Amoxicillin"],
    recordDate: new Date("2023-03-05"),
  },
  {
    patientId: patient7,
    doctorId: doctor6,
    diagnosis: "Pneumonia",
    treatment: "Hospitalization required for IV antibiotics.",
    medications: ["Levofloxacin"],
    recordDate: new Date("2023-02-14"),
  },
  {
    patientId: patient5,
    doctorId: doctor4,
    diagnosis: "Tennis Elbow",
    treatment: "Recommended physical therapy and pain relievers.",
    medications: ["Ibuprofen"],
    recordDate: new Date("2023-01-08"),
  },
  {
    patientId: patient1,
    doctorId: doctor2,
    diagnosis: "Conjunctivitis",
    treatment: "Prescribed antibiotic eye drops.",
    medications: ["Ofloxacin"],
    recordDate: new Date("2022-12-12"),
  },
  {
    patientId: patient3,
    doctorId: doctor14,
    diagnosis: "Gastritis",
    treatment: "Recommended dietary adjustments and PPIs.",
    medications: ["Pantoprazole"],
    recordDate: new Date("2022-11-21"),
  },
  {
    patientId: patient9,
    doctorId: doctor13,
    diagnosis: "Hyperthyroidism",
    treatment: "Prescribed beta-blockers and antithyroid medication.",
    medications: ["Methimazole"],
    recordDate: new Date("2022-10-17"),
  },
  {
    patientId: patient11,
    doctorId: doctor15,
    diagnosis: "Kidney Stones",
    treatment: "Advised increased hydration and medication.",
    medications: ["Tamsulosin"],
    recordDate: new Date("2022-09-05"),
  },
]);
